### ISSUE TITLE
forget ? 

### ISSUE THREAD

**Issue by LaikaSerrano** [Rodevpet/ClockNote#1]
Why does is there nothing on your project ? Did you forget commiting ? May I know what will the project be ? Thank you :)

**Comment by Rodevpet** [comment]
Infact, I would to make a notebook like JupyterNotebook who enable to write advanced latex cell and more.

For exemple, I would like to put in cell :
```latex
\usepackage{chemfig}

\xrightarrow[\chemfig{-[:-45]-[:45]O(-[:-45])}]{\chemfig{\ce{C6H5}-[:45]-[:-45]NH-[:45](-[:45])(-[:90])(-[:-45])}}
```

But I don't know, how to do this.

So, for now, the project is in stand by.

**Comment by Alkaillo** [comment]
Oh that's pretty good ! May I work with you ? I would need something like that too for my maths class

**Comment by Rodevpet** [comment]
Sure ! Anyway It's a too big project for realising alone.

**Comment by LaikaSerrano** [comment]
Yes for sure. Can we speak about that later on discord ?

**Comment by Rodevpet** [comment]
No problem
